/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package musik;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;

/**
 *
 * @author Gumilang
 */
public class CardAlbum extends javax.swing.JPanel {
    private int id_film;
    /**
     * Creates new form Card
     */
    public CardAlbum(int id_film, String nama_film, String sutradara, String rating, String path) {
        initComponents();
        labelNamaAlbum.setText(nama_film);
        labelTahunRilis.setText(sutradara);
        labelMusisi.setText(rating);
        labelPoster.setText(path);
        
        ImageIcon imageIcon = new ImageIcon(path);
        Image image = imageIcon.getImage();
        
        jPanel1.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                Image scaledImage = image.getScaledInstance(fotoAlbum.getWidth(), fotoAlbum.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newIcon = new ImageIcon(scaledImage);
                fotoAlbum.setOpaque(false);
                fotoAlbum.setBorder(BorderFactory.createEmptyBorder());
                fotoAlbum.setLayout(new BorderLayout());
                fotoAlbum.add(new JLabel(newIcon));
                }
        });
        
        this.id_film = id_film;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelPoster = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fotoAlbum = new javax.swing.JPanel();
        labelTitleNamaAlbum = new javax.swing.JLabel();
        labelNamaAlbum = new javax.swing.JLabel();
        buttonManage = new javax.swing.JButton();
        labelTitleTahunRilis = new javax.swing.JLabel();
        labelTitleMusisi = new javax.swing.JLabel();
        labelTahunRilis = new javax.swing.JLabel();
        labelMusisi = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        labelPoster.setText("jLabel3");

        fotoAlbum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout fotoAlbumLayout = new javax.swing.GroupLayout(fotoAlbum);
        fotoAlbum.setLayout(fotoAlbumLayout);
        fotoAlbumLayout.setHorizontalGroup(
            fotoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        fotoAlbumLayout.setVerticalGroup(
            fotoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        labelTitleNamaAlbum.setText("Nama album :");

        labelNamaAlbum.setText("jLabel3");

        buttonManage.setText("Manage");
        buttonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageActionPerformed(evt);
            }
        });

        labelTitleTahunRilis.setText("Tahun rilis :");

        labelTitleMusisi.setText("Musisi :");

        labelTahunRilis.setText("jLabel3");

        labelMusisi.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTitleNamaAlbum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNamaAlbum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTitleTahunRilis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTahunRilis))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTitleMusisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMusisi)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonManage)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTitleNamaAlbum)
                            .addComponent(labelNamaAlbum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTitleTahunRilis)
                            .addComponent(labelTahunRilis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTitleMusisi)
                            .addComponent(labelMusisi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonManage))
                    .addComponent(fotoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageActionPerformed
        // TODO add your handling code here:
        PanelCardAlbum mainFrame = (PanelCardAlbum) this.getTopLevelAncestor();
        File file = new File(labelPoster.getText());
        mainFrame.setTextLabelAlbum(this.id_film, labelNamaAlbum.getText(), labelTahunRilis.getText(), labelMusisi.getText(), file.getName(), file.getAbsolutePath());
    }//GEN-LAST:event_buttonManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonManage;
    private javax.swing.JPanel fotoAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMusisi;
    private javax.swing.JLabel labelNamaAlbum;
    private javax.swing.JLabel labelPoster;
    private javax.swing.JLabel labelTahunRilis;
    private javax.swing.JLabel labelTitleMusisi;
    private javax.swing.JLabel labelTitleNamaAlbum;
    private javax.swing.JLabel labelTitleTahunRilis;
    // End of variables declaration//GEN-END:variables
}
